# REINVENT4 TOML input example for sampling
run_type = "sampling"
device = "cuda:0"  # set torch device e.g. "cpu"
json_out_config = "_sampling.json"  # write this TOML to JSON
tb_logdir = "tb_logs"  # name of the TensorBoard logging directory

[parameters]
# Uncomment one of the comment blocks below.  Each generator needs a model
# file and possibly a SMILES file with seed structures.
## Reinvent: de novo sampling
model_file = "/REINVENT4/priors/reinvent.prior"
output_file = 'curate/denovo/denovo_sampling.csv'  # sampled SMILES and NLL in CSV format


num_smiles = 100  # number of SMILES to be sampled, 1 per input SMILES
unique_molecules = true  # if true remove all duplicatesd canonicalize smiles
randomize_smiles = true # if true shuffle atoms in SMILES randomly
