# REINVENT4 TOML input example for sampling
run_type = "sampling"
device = "cuda:0"  # set torch device e.g. "cpu"
json_out_config = "_sampling.json"  # write this TOML to JSON
tb_logdir = "tb_logs"  # name of the TensorBoard logging directory

[parameters]

# Uncomment one of the comment blocks below.  Each generator needs a model
# file and possibly a SMILES file with seed structures.

## Reinvent: de novo sampling
#model_file = "priors/reinvent.prior"
#output_file = 'denovo_sampling.csv'  # sampled SMILES and NLL in CSV format

## LibInvent: find R-groups for the given scaffolds
#model_file = "priors/libinvent.prior"
#smiles_file = "configs/toml/scaffolds.smi"  # 1 scaffold per line with attachment points
#output_file ="scaffold_samplig.csv"

## LinkInvent: find a linker/scaffold to link two fragments
#model_file = "priors/linkinvent.prior"
#smiles_file = "configs/toml/warheads.smi"  # 2 warheads per line separated with '|'
#output_file = "link_sampling.csv"

## Mol2Mol: find molecules similar to the provided molecules
model_file = "priors/mol2mol_medium_similarity.prior"
smiles_file = "configs/toml/mol2mol.smi"  # 1 compound per line
sample_strategy = "beamsearch"  # multinomial or beamsearch (deterministic)
temperature = 1.0 # temperature in multinomial sampling
output_file ="mol2mol_sampling.csv"

## Pepinvent
#model_file = "priors/pepinvent.prior"
#smiles_file = "pepinvent.smi"
#sample_strategy = "beamsearch"  # multinomial or beamsearch (deterministic)
#temperature = 1.0 # temperature in multinomial sampling
#tb_logdir = "tb_logs"  # name of the TensorBoard logging directory


num_smiles = 157  # number of SMILES to be sampled, 1 per input SMILES
unique_molecules = true  # if true remove all duplicatesd canonicalize smiles
randomize_smiles = true # if true shuffle atoms in SMILES randomly
