# REINVENT4 TOML input example for sampling
run_type = "sampling"
device = "cuda:0"  # set torch device e.g. "cpu"
json_out_config = "_sampling.json"  # write this TOML to JSON
tb_logdir = "tb_logs"  # name of the TensorBoard logging directory

[parameters]

## LibInvent: find R-groups for the given scaffolds
model_file = "/REINVENT4/priors/libinvent.prior"
smiles_file = "curate/input/scaffolds.smi"  # 1 scaffold per line with attachment points
output_file ="curate/scaffold/scaffold_samplig.csv"


num_smiles = 100  # number of SMILES to be sampled, 1 per input SMILES
unique_molecules = true  # if true remove all duplicatesd canonicalize smiles
randomize_smiles = true # if true shuffle atoms in SMILES randomly
